# Site settings
# title: My Personal Homepage
# description: I share my projects, blog posts, and more.
# url: https://DEAR18.github.io
# baseurl: ""  # Leave blank for root deployment (https://yourusername.github.io)

# Author details
# author:
#   name: Kaiying
#   email: smu_zky@live.com
#   github: https://github.com/DEAR18
#   linkedin: https://www.linkedin.com/in/kaiying-zhu-a520b2134

# Theme and layout
remote_theme: pages-themes/cayman@v0.2.0  # Use Cayman theme

# Markdown settings
markdown: kramdown
highlighter: rouge  # Code syntax highlighter

# Plugins (GitHub Pages-supported Jekyll plugins)
plugins:
  - jekyll-feed     # RSS feed generation
  - jekyll-sitemap  # Sitemap for SEO
  - jekyll-seo-tag  # Improved SEO metadata
  - jekyll-paginate # Pagination support
  - jekyll-remote-theme

# show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
